# vim:fileencoding=utf8:foldmethod=marker

# fonts
font_size 24.0

# terminal
background_opacity 1.0

# theme
theme "Catppucin-Macchiato"

# BEGIN_KITTY_FONTS
font_family      family="GeistMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Layout
enabled_layouts splits:split_axis=horizontal,stack

map f5 launch --location=vsplit
map f6 launch --location=hsplit
map f9 set_tab_title
map f10 detach_window ask
map f12 close_other_windows_in_tab
map kitty_mod+t new_tab_with_cwd

map ctrl+shift+t no_op
map super+t no_op

macos_option_as_alt yes
